name: test-github-action
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '3.0.3'
      - name: Restore packages
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload APK
        uses: actions/checkout@v2
        with:
          name: my-artifact
          path: build/app/outputs/flutter-apk/app-release.apk
      - run: echo "ğŸ This job's status is ${{ job.status }}."